spring.application.name=quizapp
server.port=8080

spring.data.mogodb.uri=mongodb://localhost:27017/QuizApp


# Disable JPA completely
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Thymeleaf Configuration
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.resources.static-locations=classpath:/static/

# Generate a proper secret using Base64URL encoding
# You can generate one using: openssl rand -base64 32 | tr '+/' '-_' | tr -d '='
jwt.secret=bW9uZ3VzX3NheXNfaGVsbG9fd29ybGRfbW9uZ3VzX3NheXNfaGVsbG9
jwt.expiration=86400000